// 最喜欢的歌手/作品/电影 — 多选
export const favoriteTagOptions = [
  { value: '周杰伦', label: '周杰伦' },
  { value: '林俊杰', label: '林俊杰' },
  { value: '陈奕迅', label: '陈奕迅' },
  { value: '邓紫棋', label: '邓紫棋' },
  { value: '五月天', label: '五月天' },
  { value: '王菲', label: '王菲' },
  { value: '薛之谦', label: '薛之谦' },
  { value: 'Taylor Swift', label: 'Taylor Swift' },
  { value: '三体', label: '三体' },
  { value: '活着', label: '活着' },
  { value: '小王子', label: '小王子' },
  { value: '哈利波特', label: '哈利波特' },
  { value: '你的名字', label: '你的名字' },
  { value: '千与千寻', label: '千与千寻' },
  { value: '流浪地球', label: '流浪地球' },
  { value: '复仇者联盟', label: '复仇者联盟' },
  { value: '王者荣耀', label: '王者荣耀' },
  { value: '原神', label: '原神' },
  { value: '篮球', label: '篮球' },
  { value: '足球', label: '足球' },
  { value: 'LOL', label: 'LOL' },
  { value: '二次元', label: '二次元' },
  { value: 'K-POP', label: 'K-POP' },
  { value: '摄影', label: '摄影' },
  { value: '画画', label: '画画' },
];

// 给自己的标签 — 单选
export const labelOptions = [
  { value: '学霸', label: '学霸' },
  { value: '运动健将', label: '运动健将' },
  { value: '文艺青年', label: '文艺青年' },
  { value: '开心果', label: '开心果' },
  { value: '技术宅', label: '技术宅' },
  { value: '社交达人', label: '社交达人' },
  { value: '美食家', label: '美食家' },
  { value: '旅行者', label: '旅行者' },
  { value: '追剧党', label: '追剧党' },
  { value: '游戏高手', label: '游戏高手' },
  { value: '音乐人', label: '音乐人' },
  { value: '书虫', label: '书虫' },
  { value: '班干部', label: '班干部' },
  { value: '打工人', label: '打工人' },
];
